FROM registry.access.redhat.com/ubi9:latest

RUN curl -O -L "https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-amd64"; \
    chmod +x jq-linux-amd64; \
    mv jq-linux-amd64 /usr/local/bin/jq;
