apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secret
type: Opaque
# Only one of the following fields can be set. The Operator fails to register the runner if both are provided.
# NOTE: runner-registration-token is deprecated and will be removed in GitLab 18.0. You should use runner-token instead.
stringData:
  #runner-token: glrt-KRarBrxHzZRyCy-yJvrU
  #runner-token: REPLACE_ME # your project runner token
  runner-registration-token: glrt-KRarBrxHzZRyCy-yJvrU # your project runner secret
